name: Qodo Merge PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 

      - name: Run Qodo Merge Review
        uses: qodo-ai/pr-agent@db5138dc428575c0c2245f2f04b58921b2ecc825
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

